### ISSUE TITLE
优化环境变量和文档

### ISSUE THREAD

**Issue by hailiang-wang** [wechaty/plugin-chatopera#6]

**Comment by huan** [comment]
When I'm reviewing 

- https://github.com/kaiyuanshe/osschat/pull/155/

I found that we are using environment variables from this plugin:

https://github.com/wechaty/wechaty-chatopera/blob/55d32185ab3af76add577de0c435348095580983/src/normalize-config.ts#L25-L50

I believe a plugin should not read the environment variable, it should only accept a plugin config from its args.

If we want to pass the environment variable to the plugin, we should do this outside the plugin, because there might be many different wechaty instances that use this plugin at the same time, and we need to keep the plugin to be decoupled with the environment.

**Comment by hailiang-wang** [comment]
> When I'm reviewing
> 
> * [Enable Chatopera plugin with ENVIRONMENT variables for deliver more chat skills in OSSChat kaiyuanshe/osschat#155](https://github.com/kaiyuanshe/osschat/pull/155)
> 
> I found that we are using environment variables from this plugin:
> 
> https://github.com/wechaty/wechaty-chatopera/blob/55d32185ab3af76add577de0c435348095580983/src/normalize-config.ts#L25-L50
> 
> I believe a plugin should not read the environment variable, it should only accept a plugin config from its args.
> 
> If we want to pass the environment variable to the plugin, we should do this outside the plugin, because there might be many different wechaty instances that use this plugin at the same time, and we need to keep the plugin to be decoupled with the environment.

agree, fix it later.
